# Generated by Django 4.0.1 on 2023-10-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone_number'),
        ('user', '0003_alter_user_phone_number_profileinfolocationbd_and_more'),
    ]

    operations = [
    ]
