# Generated by Django 4.0.1 on 2023-10-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20231001_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
