# Generated by Django 4.0.1 on 2023-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo1',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
