# Generated by Django 4.0.1 on 2023-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profilecomplete1_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo1',
            name='profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto/'),
        ),
        migrations.AddField(
            model_name='profileinfoexperience',
            name='durationstayexperience',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
